### ISSUE TITLE
[Bug] ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by Kristinita** [robinchenyu/imagepaste#6]
### 1. Summary

I can not begin to use ImagePaste, I get stack trace.

### 2. Expected behavior

Successful begin to use ImagePaste.

### 3. Actual behavior

```python
Traceback (most recent call last):
  File "D:\Sublime Text 3 x64\Data\Packages\ImagePaste\ImagePaste.py", line 5, in <module>
    from PIL import ImageGrab
  File "D:\Sublime Text 3 x64\Data\Packages\ImagePaste\PIL\ImageGrab.py", line 18, in <module>
    from PIL import Image
  File "D:\Sublime Text 3 x64\Data\Packages\ImagePaste\PIL\Image.py", line 66, in <module>
    from PIL import _imaging as core
ImportError: DLL load failed: %1 is not a valid Win32 application.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Sublime Text 3 x64\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "D:\Sublime Text 3 x64\Data\Packages\ImagePaste\ImagePaste.py", line 10, in <module>
    from PIL import ImageGrab
  File "D:\Sublime Text 3 x64\Data\Packages\ImagePaste\PIL\ImageGrab.py", line 18, in <module>
    from PIL import Image
  File "D:\Sublime Text 3 x64\Data\Packages\ImagePaste\PIL\Image.py", line 66, in <module>
    from PIL import _imaging as core
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

### 4. Steps to reproduce

I reproduce the problem in a version of Sublime Text without plugins and user settings.

I install ImagePaste → I get stack trace in console → I restart Sublime Text → `image_paste` command don't work for me.

### 5. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126
**ImagePaste:**
v1.0.3

Thanks.

**Comment by robinchenyu** [comment]
Could you try below test using your system python
1. Install PIL lib for your system python 
```python
pip install pillow
```
2. save below as test.py
```python
try:
    from PIL import ImageGrab
    from PIL import ImageFile
except ImportError:
    import sys
    from PIL import ImageGrab
    from PIL import ImageFile

ImageFile.LOAD_TRUNCATED_IMAGES = True
im = ImageGrab.grabclipboard()
im.save('pic.png','PNG')
```
3. Take a screenshot and save to clipboard, then try below command
```bash
python .\test.py
```

Thanks!

**Comment by Kristinita** [comment]
@robinchenyu ,

```python
PS D:\Test> python .\test.py
Traceback (most recent call last):
  File ".\test.py", line 11, in <module>
    im.save('pic.png', 'PNG')
AttributeError: 'NoneType' object has no attribute 'save'
```

Thanks.

**Comment by robinchenyu** [comment]
The error maybe clipboard is empty, pls take screenshot before run test.py

**Comment by firezheng** [comment]
我也遇到了同样的问题。
